/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  Overrides,
  PayableOverrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import type { TypedEventFilter, TypedEvent, TypedListener } from "./common";

interface DexSwapInterface extends ethers.utils.Interface {
  functions: {
    "buyTokens()": FunctionFragment;
    "getBuyRate()": FunctionFragment;
    "getMaximumBuy()": FunctionFragment;
    "getMaximumSell()": FunctionFragment;
    "getSellRate()": FunctionFragment;
    "getTotalSales()": FunctionFragment;
    "sellTokens(uint256)": FunctionFragment;
    "token()": FunctionFragment;
  };

  encodeFunctionData(functionFragment: "buyTokens", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "getBuyRate",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getMaximumBuy",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getMaximumSell",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getSellRate",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getTotalSales",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "sellTokens",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "token", values?: undefined): string;

  decodeFunctionResult(functionFragment: "buyTokens", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getBuyRate", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getMaximumBuy",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getMaximumSell",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getSellRate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTotalSales",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "sellTokens", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "token", data: BytesLike): Result;

  events: {
    "TokensPurchased(address,address,uint256,uint256)": EventFragment;
    "TokensSold(address,address,uint256,uint256)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "TokensPurchased"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "TokensSold"): EventFragment;
}

export type TokensPurchasedEvent = TypedEvent<
  [string, string, BigNumber, BigNumber] & {
    account: string;
    token: string;
    amount: BigNumber;
    rate: BigNumber;
  }
>;

export type TokensSoldEvent = TypedEvent<
  [string, string, BigNumber, BigNumber] & {
    account: string;
    token: string;
    amount: BigNumber;
    rate: BigNumber;
  }
>;

export class DexSwap extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: DexSwapInterface;

  functions: {
    buyTokens(
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    getBuyRate(overrides?: CallOverrides): Promise<[BigNumber]>;

    getMaximumBuy(overrides?: CallOverrides): Promise<[BigNumber]>;

    getMaximumSell(overrides?: CallOverrides): Promise<[BigNumber]>;

    getSellRate(overrides?: CallOverrides): Promise<[BigNumber]>;

    getTotalSales(overrides?: CallOverrides): Promise<[BigNumber]>;

    sellTokens(
      _amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    token(overrides?: CallOverrides): Promise<[string]>;
  };

  buyTokens(
    overrides?: PayableOverrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  getBuyRate(overrides?: CallOverrides): Promise<BigNumber>;

  getMaximumBuy(overrides?: CallOverrides): Promise<BigNumber>;

  getMaximumSell(overrides?: CallOverrides): Promise<BigNumber>;

  getSellRate(overrides?: CallOverrides): Promise<BigNumber>;

  getTotalSales(overrides?: CallOverrides): Promise<BigNumber>;

  sellTokens(
    _amount: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  token(overrides?: CallOverrides): Promise<string>;

  callStatic: {
    buyTokens(overrides?: CallOverrides): Promise<void>;

    getBuyRate(overrides?: CallOverrides): Promise<BigNumber>;

    getMaximumBuy(overrides?: CallOverrides): Promise<BigNumber>;

    getMaximumSell(overrides?: CallOverrides): Promise<BigNumber>;

    getSellRate(overrides?: CallOverrides): Promise<BigNumber>;

    getTotalSales(overrides?: CallOverrides): Promise<BigNumber>;

    sellTokens(_amount: BigNumberish, overrides?: CallOverrides): Promise<void>;

    token(overrides?: CallOverrides): Promise<string>;
  };

  filters: {
    "TokensPurchased(address,address,uint256,uint256)"(
      account?: null,
      token?: null,
      amount?: null,
      rate?: null
    ): TypedEventFilter<
      [string, string, BigNumber, BigNumber],
      { account: string; token: string; amount: BigNumber; rate: BigNumber }
    >;

    TokensPurchased(
      account?: null,
      token?: null,
      amount?: null,
      rate?: null
    ): TypedEventFilter<
      [string, string, BigNumber, BigNumber],
      { account: string; token: string; amount: BigNumber; rate: BigNumber }
    >;

    "TokensSold(address,address,uint256,uint256)"(
      account?: null,
      token?: null,
      amount?: null,
      rate?: null
    ): TypedEventFilter<
      [string, string, BigNumber, BigNumber],
      { account: string; token: string; amount: BigNumber; rate: BigNumber }
    >;

    TokensSold(
      account?: null,
      token?: null,
      amount?: null,
      rate?: null
    ): TypedEventFilter<
      [string, string, BigNumber, BigNumber],
      { account: string; token: string; amount: BigNumber; rate: BigNumber }
    >;
  };

  estimateGas: {
    buyTokens(
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    getBuyRate(overrides?: CallOverrides): Promise<BigNumber>;

    getMaximumBuy(overrides?: CallOverrides): Promise<BigNumber>;

    getMaximumSell(overrides?: CallOverrides): Promise<BigNumber>;

    getSellRate(overrides?: CallOverrides): Promise<BigNumber>;

    getTotalSales(overrides?: CallOverrides): Promise<BigNumber>;

    sellTokens(
      _amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    token(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    buyTokens(
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    getBuyRate(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getMaximumBuy(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getMaximumSell(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getSellRate(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getTotalSales(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    sellTokens(
      _amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    token(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
